commands:
  - name: c1
    command: yarn dev
    filters:
      - "{regex}"
      - "{regex}"
    checkpoint:
      - name: ch1
        command: "curl http://localhost:8080"
    watch:
      - "file1"
      - "file2"
      - "file3"

  - name: c2
    command: node index.js
    filters:
      - "{regex}"
    watch:
      - "file1"
      - "file2"
      - "file3"
    depends_on: 
      - c1.ch1

  - name: c3
    command: cmatrix
    filters:
      - "{regex}"
    watch:
      - "file1"
      - "file2"
      - "file3"

